# NUMPY

In [26]:
!pip install numpy

## Import Numpy

In [1]:
import numpy as np

In [29]:
c = np.array([1,2,3])

In [30]:
c

array([1, 2, 3])

## One Dimensional Array

### Indexing dan Slicing

In [36]:
c[1]

2

In [43]:
array_1 = np.array([1,2,3,4,5,6,7,8]) #one dimensional

In [44]:
array_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
array_1[3:] #slicing sama seperti list

[4, 5, 6, 7, 8]

In [153]:
array_1.shape #hasil adalah baris, kolom

(8,)

## Two Dimensional Array Consist of List of List

In [51]:
list_of_list = [[1,2,3],[4,5,6],[7,8,9]]
array_2 = np.array(list_of_list)
np.array(list_of_list)
array_2.shape

(3, 3)

In [58]:
list_of_list2 = [[1,2],[3,4],[5,6]]
array_3 = np.array(list_of_list2)
print(np.array(list_of_list2))
print(array_3.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
3 baris dan 2 kolom

## Creating Array

In [57]:
# np.zeros
print(np.zeros(8)) #menghasilkan one dimensional array dengan 8 angka 0
print(np.zeros([3,2])) ##menghasilkan two dimensional array

[0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [60]:
#np.ones
print(np.ones(4))
print(np.ones((4,2)))

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [68]:
#np.empty
print(np.empty(5)) #angka random yang sangat kecil
print(np.empty((3,2)))

[2.12199579e-314 6.36598737e-314 1.06099790e-313 1.48539705e-313
 1.90979621e-313]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [67]:
#np.arange
print(np.arange(10))
print(np.arange(0,10,2)) #start,stop,step > konsep seperti slicing

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [76]:
c = np.array([1,2,3,4,5,6,7,8,9])

#append
print(np.append(c,[10,11]))

#delete
print(np.delete(c,2))

#sort
print(np.sort(c))

[ 1  2  3  4  5  6  7  8  9 10 11]
[1 2 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [83]:
d = np.zeros((2,2))

#ndim
print(c.ndim)
print(d.ndim)

#size
print(c.size)
print(d.size)

#reshape
print(c.reshape(3,3))

1
2
9
4
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
array_3 = np.array([[1,2,3,4]])
array_3.shape

(1, 4)

In [88]:
#np.newaxis
array_4 = np.array([4,5,6])
print(array_4[np.newaxis]) #default menambah axis 1 > kolom
print(array_4[:,np.newaxis]) #berubah menjadi 2 dimensi

[[4 5 6]]
[[4]
 [5]
 [6]]


In [91]:
#np.expamd_dims
array_5 = np.array([1,2,3,4,5,6])
array_6 = np.expand_dims(array_5,axis=1)
print(array_5)
print(array_6)
print(array_6.shape)

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


## Operasi Matematika Pada Array

In [2]:
array_5 = np.array([1,2,3,4,5,6])
print(array_5*2)
array_7 = np.array([[1,2,3],[4,5,6]])
print(array_7-2)

[ 2  4  6  8 10 12]
[[-1  0  1]
 [ 2  3  4]]


## Filtering Array

In [3]:
print(array_7[array_7 > 5])
print(array_7[array_7 == 3])
print(array_7[array_7 < 4])

[6]
[3]
[1 2 3]


## hstack, vstack, hsplit, vsplit

In [4]:
array_14 = np.array([3,4,5,6,7])
array_15 = np.array([7,8,9,10,11])

#stack vertikal
print('Stack secara vertikal')
print(np.vstack([array_14,array_15]))

#stack horizontal
print('Stack secara horizontal')
print(np.hstack([array_14,array_15]))

Stack secara vertikal
[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
Stack secara horizontal
[ 3  4  5  6  7  7  8  9 10 11]


In [127]:
#split
array_16 = np.array([3,4,5,6,7,8])
array_split = np.hsplit(array_16,2)
(array_split)

[array([3, 4, 5]), array([6, 7, 8])]

In [5]:
array_17 = np.array([[3,4,5,6,7],[7,8,9,10,11]])
print(array_17)
print(array_17.shape)

#hsplit
print('Horizontal split')
print(np.hsplit(array_17,5))

#vsplit
print('Vertikal Split')
print(np.vsplit(array_17,2))

[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
(2, 5)
Horizontal split
[array([[3],
       [7]]), array([[4],
       [8]]), array([[5],
       [9]]), array([[ 6],
       [10]]), array([[ 7],
       [11]])]
Vertikal Split
[array([[3, 4, 5, 6, 7]]), array([[ 7,  8,  9, 10, 11]])]


## Operasi Aritmetik Antar 2 Array

In [145]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
print(array_a+array_b)
print(array_a.sum())

[5 7 9]
6
6


In [148]:
array_c = np.array([[3,4,5,6,7],[7,8,9,10,11]])
print(array_c.sum(axis=0)) #sum ke bawah
print(array_c.sum(axis=1)) #sum ke samping

[10 12 14 16 18]
[25 45]


In [150]:
print(array_a.max())
print(array_b.max())
print(array_c.max())
print(array_a.max(axis=0))

3
6
11
3


## Transpose

In [152]:
array_c = np.array([[3,4,5,6,7],[7,8,9,10,11]])
print(array_c)
print(array_c.T)

[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
[[ 3  7]
 [ 4  8]
 [ 5  9]
 [ 6 10]
 [ 7 11]]


In [6]:
array_d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#sebelum transpose
print('Array sebelum transpose')
print(array_d)
print(array_d.shape)

#setelah transpose
print('Array setelah transpose')
print(array_d.T)
print(array_d.T.shape)

Array sebelum transpose
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
Array setelah transpose
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
(4, 3)


In [7]:
#mengambil angka random untuk array
array_random = np.random.random([3,2])
print(array_random)
print(array_random.flatten())

[[0.8762085  0.0250401 ]
 [0.95403704 0.50209853]
 [0.24495854 0.25407102]]
[0.8762085  0.0250401  0.95403704 0.50209853 0.24495854 0.25407102]


## Numpy Math Formulas

In [164]:
array_random = np.random.random([3,2])*100
print(array_random)
#sum
np.sum(array_random)

[[29.44377678 99.1940388 ]
 [64.62410509  3.19912937]
 [37.88250586 18.31825544]]


252.66181134644467

In [165]:
#square
np.square(9)

81

In [166]:
#sqrt
np.sqrt(9)

3.0

In [168]:
#log
a = np.log(10000)
print(a)

9.210340371976184


# KUIS

## Prime Number Generator Based on Interval

In [9]:
# First, we will take the input:  
lower_value = int(input ("Please, Enter the Lowest Range Value: "))  
upper_value = int(input ("Please, Enter the Upper Range Value: "))  
  
print ("The Prime Numbers in the range are: ")  
for number in range (lower_value, upper_value + 1):  
    if number > 1:  
        for i in range (2, number):  
            if (number % i) == 0:  
                break  
        else:  
            print (number)

Please, Enter the Lowest Range Value:  1
Please, Enter the Upper Range Value:  30


The Prime Numbers in the range are: 
2
3
5
7
11
13
17
19
23
29


## Calculator Function Based on Operators

In [11]:
def calc(a,b,c):
    if (a.isnumeric() == True) and (c.isnumeric() == True) :
        a = int(a)
        c = int(c)
        if b == 'x' :
            print('Hasil dari', a, b, c, 'adalah', a*c)
        elif b == '+' :
            print('Hasil dari', a, b, c, 'adalah', a+c)
        elif b == ':' :
            print('Hasil dari', a, b, c, 'adalah', a/c)
        elif b == "-" :
            print('Hasil dari', a, b, c, 'adalah', a - c)
        elif b == "^" :
            print('Hasil dari', a, b, c, 'adalah', a**c)
        else :
            print('operator', b, 'tidak ditemukan')
    else :
        print('salah')

a = (input('masukkan angka1= '))
b = (input('masukkan operator= '))
c = (input('masukkan angka2= '))

calc(a,b,c)

masukkan angka1=  10
masukkan operator=  x
masukkan angka2=  3


Hasil dari 10 x 3 adalah 30
